### ISSUE TITLE
Uncaught TypeError: this.resolve is not a function

### ISSUE THREAD

**Issue by zhaocai** [t9md/atom-choose-pane#1]
## Steps to reproduce:
1. Open Command Palette
2. Use Command `Window: Toggle Invisibles`

**Atom Version**: 1.9.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [choose-pane](https://github.com/t9md/atom-choose-pane) package, v0.5.0
### Stack Trace

Uncaught TypeError: this.resolve is not a function

```
At /C:/Users/Zhao/.atom/packages/choose-pane/lib/input.coffee:90

TypeError: this.resolve is not a function
    at choose-pane-input.Input.confirm (file:///C:/Users/Zhao/.atom/packages/choose-pane/lib/input.coffee:41:6)
    at file:///C:/Users/Zhao/.atom/packages/choose-pane/lib/input.coffee:15:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\text-editor.js:346:32
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at DisplayLayer.module.exports.DisplayLayer.emitDidChangeSyncEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:366:27)
    at DisplayLayer.module.exports.DisplayLayer.reset (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:227:12)
    at TextEditor.module.exports.TextEditor.resetDisplayLayer (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\text-editor.js:368:32)
    at C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:887:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:227:14)
    at atom-workspace.commandRegistry.add.window:toggle-invisibles (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\register-default-commands.js:205:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Zhao\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -0:32.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:32.7.0 window:toggle-invisibles (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite)
  2x -0:31.5.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:29.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:29 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:26.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 window:toggle-invisibles (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite)
  2x -0:25.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
 19x -0:21 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:05.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:05.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite.is-focused)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 window:toggle-invisibles (atom-text-editor.editor.vim-mode-plus.normal-mode.vim-mode-plus-move-selected-text-overwrite)
```

```
```

**Comment by t9md** [comment]
Thanks for reporting

**Comment by zhaocai** [comment]
Thanks, it works now.
